version1
jscaicedom/PokemonProject-Angular-Talos pull request #1
Opened 2020-11-04 14:39 UTC by jscaicedom

2020-11-04 15:17 UTC, mflorezr reviewed
You could try to avoid empty subscribes

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/comparemodal/comparemodal.component.css
> +  background: #5c6269; }
You can use variables to hex color codes

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/comparemodal/comparemodal.component.css
> +
get ride of this line

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/graphics/graphics.component.ts
> +  public chartColors: Array<any> = [
You need to add a type to the variables

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/header/header.component.html
> +
get rid of this line

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/header/header.component.ts
> +    console.log(text);
i don't think you need this

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/home/home.component.ts
> +      )
You could do this inside the subscribe as a good practice

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/modal/modal.component.ts
> +  }
be careful with identation

2020-11-04 15:17 UTC, mflorezr commented on src/environments/environment.ts
> +  selectedUrl: 'https://pokeapi.co/api/v2/pokemon/',
this url should be at environment.prod.ts

2020-11-04 15:17 UTC, mflorezr commented on src/app/components/home/home.component.html
> +            src="https://raw.githubusercontent.com/PokeAPI/sprites/146c91287ad01f6e15315bbd733fd7442c91fe6d/sprites/pokemon/{{favorite + 1}}.png"
You could use a environment variable for the url

2020-11-04 15:17 UTC, mflorezr commented on src/app/services/pokemons-http.service.ts
> +  }
As a good practice you should put the return type of method

2020-11-04 20:45 UTC, hackeo1 requested changes
- divide the app in different modules
- for future projects: use a css preprocessor

2020-11-04 20:45 UTC, hackeo1 commented on angular.json
> +              "./node_modules/hammerjs/hammer.min.js"
dependency scripts should be loaded in the project code (main.ts)

2020-11-04 20:45 UTC, hackeo1 commented on src/app/app.component.ts
> +  title = 'NgrxProject-Talos';
remove unused variable

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/comparemodal/comparemodal.component.html
> +      femenino
don't use Spanish

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/comparemodal/comparemodal.component.ts
> +  state$: Observable<AppState>;
remove unused attribute

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/comparemodal/comparemodal.component.ts
> +      .pipe(select('state'))
use selectors

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/graphics/graphics.component.html
> +<div class="modal-footer" style="display: block">
don't use inline styles

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/graphics/graphics.component.ts
> +  public chartOptions: any = {
don't use any to type

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/graphics/graphics.component.ts
> +  public chartColors: Array<object> = [
avoid using object as type

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/graphics/graphics.component.ts
> +      .pipe(select('state'))
use selectors

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/header/header.component.html
> +    <input #searchText (input)="change(searchText.value)" type="search" name="buscar" class="header-input"
don't use Spanish

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/header/header.component.ts
> +  change(text: string) {
describe what you are changing here

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/home/home.component.html
> +          <img class="pokemon-image" src="{{imgUrl + favorite}}.png" alt="Pokemon{{favorite}}" />
use input instead of interpolation for attributes

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/home/home.component.ts
> +      .pipe(select('state'))
use selectors

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/modal/modal.component.ts
> +      .pipe(select('state'))
use selectors

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/pokemons/pokemons.component.html
> +        <img class="pokemon-image" src="{{imgUrl + pokemon.index}}.png" (click)="open(pokemon.name)"
use input instead of interpolation, if there is no input for the attribute use the generic input [attr.attributename]

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/pokemons/pokemons.component.ts
> +      .pipe(select('state'))
use selectors

2020-11-04 20:45 UTC, hackeo1 commented on src/app/components/pokemons/pokemons.component.ts
> +      ? window.alert('You just can select 5 favorite Pokemons')
don't use window alerts

2020-11-04 20:45 UTC, hackeo1 commented on src/app/ngrx/effects/pokemons.effects.ts
> +                id: data['id'],
avoid the use of [] to access object attributes

2020-11-04 20:45 UTC, hackeo1 commented on src/app/services/pokemons-http.service.ts
> +  getDescription(url: string): Observable<Object> {
avoid the use of object to type

2020-11-09 22:34 UTC, hackeo1 requested changes

2020-11-09 22:34 UTC, hackeo1 commented on src/app/modal/components/modal/modal.component.html
> +  <ng-template #thenBlock>
Change the name to describe what is inside, not where it is used

2020-11-09 22:34 UTC, hackeo1 commented on src/app/modal/components/modal/modal.component.html
> +  <ng-template #elseBlock>
Change the name to describe what is inside, not where it is used

2020-11-09 22:34 UTC, hackeo1 commented on src/app/modal/components/modal/modal.component.ts
> +  @Input() name;
add type

2020-11-09 22:34 UTC, hackeo1 commented on src/app/pokemon/components/pokemons/pokemons.component.html
> +    <div *ngFor="let pokemon of pokemons; index as i" class="pokemon-container">
don't use single character variables

2020-11-09 22:34 UTC, hackeo1 commented on src/app/pokemon/components/pokemons/pokemons.component.html
> +    <p class="compare-subtitle">
these should not be p tags

2020-11-09 22:34 UTC, hackeo1 commented on src/app/pokemon/components/pokemons/pokemons.component.ts
> +      : this.store.dispatch(addFavorite({ index }));
if you need to use more than one ternary, it is better to use if else statements, don't use ternary to run functions, try to keep it only to assign values to variables

2020-11-09 22:34 UTC, hackeo1 commented on src/app/services/pokemons-http.service.ts
> +  getDescription(url: string) {
add returning type

2020-11-09 22:34 UTC, hackeo1 commented on src/app/services/pokemons-http.service.ts
> +  getSelectedPokemon(name: string) {
add returning type

2020-11-09 22:34 UTC, hackeo1 commented on src/app/services/pokemons-http.service.ts
> +  getPokemons(offset: number) {
add returning type

2020-11-09 22:34 UTC, hackeo1 commented on src/main.ts
> +import '../node_modules/hammerjs/hammer.min.js';
try
import 'chart.js';
import 'hammerjs';

2020-11-10 14:22 UTC, hackeo1 approved these changes

2020-11-10 14:29 UTC, merged